development:
  adapter: postgresql
  encoding: utf8
  database: bookmarks_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: bookmarks_test
  pool: 5
  timeout: 5000
  host: localhost
